# Generated by Django 4.2.3 on 2024-04-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcast_title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('clip_url', models.CharField(max_length=255)),
                ('next', models.IntegerField(null=True)),
                ('prev', models.IntegerField(null=True)),
            ],
        ),
    ]
