# Generated by Django 4.2.3 on 2024-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='next',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='podcast_title',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='prev',
        ),
    ]
